---
# Without using the certbot docker container

# Note: This throws a number of errors and doesn't work as it should

- pip:
    name: acme-tiny

- openssl_privatekey:
    path: "{{ secured_cert_dir }}/private/account.pem"
    size: 2048
  become: yes

- name: Generate a Let's Encrypt Certificate
  openssl_certificate:
    provider:             "acme"
    csr_path:             "{{ secured_cert_dir }}/csr/{{ secured_host_name }}.csr"
    privatekey_path:      "{{ secured_cert_dir }}/private/{{ secured_common_name }}.pem"
    acme_accountkey_path: "{{ secured_cert_dir }}/private/account.pem"
    acme_challenge_path:  "{{ secured_cert_dir }}/challenges"
    path:                 "{{ secured_cert_dir }}/crt/{{ secured_host_name }}.crt"
    force: True
  become: yes