---
- name: Run certbot in docker
  docker_container:
    name:  certbot
    image: certbot/{{ secured_cb_docker_image }}:latest
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/var/lib/letsencrypt:/var/lib/letsencrypt"
      - '{{ "{}:{}".format( secured_cert_dir, secured_cert_dir) }}'
    command: "{{ secured_cb_command }}"
    state: started
    env:
      TZ: America/New_York
  delegate_to: localhost

- name: Wait on certbot to result
  command: docker wait certbot
  delegate_to: localhost

- name: Copy the certbot cert to the certs folder
  copy:
    src: "/etc/letsencrypt/live/{{ secured_host_name }}/fullchain.pem"
    dest: "{{ secured_cert_dir }}/crt/{{ secured_host_name }}.pem"
    remote_src: no

- name: Copy the certbot key to the private folder
  copy:
    src: "/etc/letsencrypt/live/{{ secured_host_name }}/privkey.pem"
    dest: "{{ secured_cert_dir }}/private/{{ secured_host_name }}.pem"
    remote_src: no
